spring.boot.admin.url: http://localhost:8000 
management.security.enabled: false

# abaixo as configuracoes da segurança com JWT
app:
  name: truffles-api
jwt:
  header: Authorization
  expires_in: 86400 # 500 # 5 minutes
  mobile_expires_in: 86400 # 600 # 10 minutes
  secret: algconsulting