Insert Into tb_state (ibge_code,initial,name) Values(12,'AC','Acre');  
Insert Into tb_state (ibge_code,initial,name) Values(27,'AL','Alagoas');  
Insert Into tb_state (ibge_code,initial,name) Values(13,'AM','Amazonas');
Insert Into tb_state (ibge_code,initial,name) Values(16,'AP','Amapá');
Insert Into tb_state (ibge_code,initial,name) Values(29,'BA','Bahia');
Insert Into tb_state (ibge_code,initial,name) Values(23,'CE','Ceará');
Insert Into tb_state (ibge_code,initial,name) Values(53,'DF','Distrito Federal');
Insert Into tb_state (ibge_code,initial,name) Values(32,'ES','Espírito Santo');
Insert Into tb_state (ibge_code,initial,name) Values(52,'GO','Goiás');
Insert Into tb_state (ibge_code,initial,name) Values(21,'MA','Maranhão');
Insert Into tb_state (ibge_code,initial,name) Values(31,'MG','Minas Gerais');
Insert Into tb_state (ibge_code,initial,name) Values(50,'MS','Mato Grosso do Sul');
Insert Into tb_state (ibge_code,initial,name) Values(51,'MT','Mato Grosso');
Insert Into tb_state (ibge_code,initial,name) Values(15,'PA','Pará');
Insert Into tb_state (ibge_code,initial,name) Values(25,'PB','Paraíba');
Insert Into tb_state (ibge_code,initial,name) Values(26,'PE','Pernambuco');
Insert Into tb_state (ibge_code,initial,name) Values(22,'PI','Piauí');
Insert Into tb_state (ibge_code,initial,name) Values(41,'PR','Paraná');
Insert Into tb_state (ibge_code,initial,name) Values(33,'RJ','Rio de Janeiro');
Insert Into tb_state (ibge_code,initial,name) Values(24,'RN','Rio Grande do Norte');
Insert Into tb_state (ibge_code,initial,name) Values(11,'RO','Rondônia');
Insert Into tb_state (ibge_code,initial,name) Values(14,'RR','Roraima');
Insert Into tb_state (ibge_code,initial,name) Values(43,'RS','Rio Grande do Sul');
Insert Into tb_state (ibge_code,initial,name) Values(42,'SC','Santa Catarina');
Insert Into tb_state (ibge_code,initial,name) Values(28,'SE','Sergipe');
Insert Into tb_state (ibge_code,initial,name) Values(35,'SP','São Paulo');
Insert Into tb_state (ibge_code,initial,name) Values(17,'TO','Tocantins');
