@startuml

title __REPOSITORIES's Class Diagram__\n

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.AccountRepository {
          {abstract} + findByEmail()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.AddressRepository {
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.CategoryRepository {
          {abstract} + findById()
          {abstract} + findByName()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.CityRepository {
          {abstract} + findByName()
          {abstract} + findByState()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.DeliveryRepository {
          {abstract} + findByOrder()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.GroupRepository {
          {abstract} + findByIdOrName()
          {abstract} + findByName()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.ItemRepository {
          {abstract} + findByCategory()
          {abstract} + findByName()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.OrderItemRepository {
          {abstract} + findByOrder()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.OrderRepository {
          {abstract} + findByAccount()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.PaymentRepository {
          {abstract} + findByOrder()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.PriceRepository {
          {abstract} + findByItem()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.StateRepository {
          {abstract} + findByUf()
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace repositories {
      interface br.com.alg.trufflesapi.repositories.TaxDeliveryRepository {
          {abstract} + findByDistanceBetween()
          {abstract} + findByDistanceGreaterThanAndMaxDistanceLessThanEqual()
          {abstract} + findByValue()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
