@startuml

title __DTO's Class Diagram__\n

  namespace br.com.alg.trufflesapi {
    namespace model {
      namespace dto {
        class br.com.alg.trufflesapi.model.dto.AccountDTO {
            - addresses : List<Address>
            - email : String
            - id : Long
            - imageUrl : String
            - name : String
            - password : String
            - register : String
            {static} - serialVersionUID : long
            + AccountDTO()
            + AccountDTO()
            + getAddresses()
            + getEmail()
            + getId()
            + getImageUrl()
            + getName()
            + getPassword()
            + getRegister()
            + setAddresses()
            + setEmail()
            + setId()
            + setImageUrl()
            + setName()
            + setPassword()
            + setRegister()
        }
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace model {
      namespace dto {
        class br.com.alg.trufflesapi.model.dto.ItemDTO {
            - date : Date
            - description : String
            - id : Long
            - imageUrl : String
            - name : String
            - price : Double
            - prices : List<Price>
            {static} - serialVersionUID : long
            + ItemDTO()
            + ItemDTO()
            + ItemDTO()
            + getCategory()
            + getDate()
            + getDescription()
            + getId()
            + getImageUrl()
            + getName()
            + getPrice()
            + getPrices()
            + setCategory()
            + setDate()
            + setDescription()
            + setId()
            + setImageUrl()
            + setName()
            + setPrice()
            + setPrices()
        }
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace model {
      namespace dto {
        class br.com.alg.trufflesapi.model.dto.OrderDTO {
            {static} - serialVersionUID : long
        }
      }
    }
  }
  

  namespace br.com.alg.trufflesapi {
    namespace model {
      namespace dto {
        class br.com.alg.trufflesapi.model.dto.TaxDeliveryDTO {
            - distance : Double
            - distanceMax : Double
            - id : Long
            {static} - serialVersionUID : long
            - value : Double
            + TaxDeliveryDTO()
            + getDistance()
            + getDistanceMax()
            + getId()
            + getValue()
            + setDistance()
            + setDistanceMax()
            + setId()
            + setValue()
        }
      }
    }
  }
  

  br.com.alg.trufflesapi.model.dto.AccountDTO .up.|> java.io.Serializable
  br.com.alg.trufflesapi.model.dto.ItemDTO .up.|> java.io.Serializable
  br.com.alg.trufflesapi.model.dto.ItemDTO o-- br.com.alg.trufflesapi.model.Category : category
  br.com.alg.trufflesapi.model.dto.OrderDTO .up.|> java.io.Serializable
  br.com.alg.trufflesapi.model.dto.TaxDeliveryDTO .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
